"""update Room model

Revision ID: 174b1c38f0e1
Revises: 89b986ff07c0
Create Date: 2024-10-29 16:40:19.841297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '174b1c38f0e1'
down_revision: Union[str, None] = '89b986ff07c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('hotel_id', sa.Integer(), nullable=False))
    op.add_column('room', sa.Column('name', sa.String(), nullable=False))
    op.add_column('room', sa.Column('description', sa.String(), nullable=True))
    op.add_column('room', sa.Column('price', mysql.DECIMAL(), nullable=False))
    op.add_column('room', sa.Column('services', sa.JSON(), nullable=True))
    op.add_column('room', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'room', 'hotel', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'quantity')
    op.drop_column('room', 'services')
    op.drop_column('room', 'price')
    op.drop_column('room', 'description')
    op.drop_column('room', 'name')
    op.drop_column('room', 'hotel_id')
    # ### end Alembic commands ###
